// <auto-generated />
using BibliotecaMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaMVC.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260618205601_AddAdmin")]
    partial class AddAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BibliotecaMVC.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Senha = "admin123",
                            Usuario = "admin"
                        });
                });

            modelBuilder.Entity("BibliotecaMVC.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoPublicacao = 1899,
                            Autor = "Machado de Assis",
                            Categoria = "Literatura",
                            Descricao = "Um dos maiores clássicos da literatura brasileira, narrado pelo enigmático Bentinho.",
                            Disponivel = true,
                            ISBN = "978-85-0000-001-1",
                            Titulo = "Dom Casmurro"
                        },
                        new
                        {
                            Id = 2,
                            AnoPublicacao = 1988,
                            Autor = "Stephen Hawking",
                            Categoria = "Ciências",
                            Descricao = "Uma jornada pelo universo explicada de forma acessível pelo gênio Stephen Hawking.",
                            Disponivel = true,
                            ISBN = "978-85-0000-002-2",
                            Titulo = "Uma Breve História do Tempo"
                        },
                        new
                        {
                            Id = 3,
                            AnoPublicacao = 1943,
                            Autor = "Antoine de Saint-Exupéry",
                            Categoria = "Infantil",
                            Descricao = "Um conto poético e filosófico sobre amizade, amor e os mistérios da vida.",
                            Disponivel = false,
                            ISBN = "978-85-0000-003-3",
                            Titulo = "O Pequeno Príncipe"
                        },
                        new
                        {
                            Id = 4,
                            AnoPublicacao = 2011,
                            Autor = "Yuval Noah Harari",
                            Categoria = "História",
                            Descricao = "Uma fascinante narrativa da história da humanidade desde a pré-história até os dias atuais.",
                            Disponivel = true,
                            ISBN = "978-85-0000-004-4",
                            Titulo = "Sapiens"
                        },
                        new
                        {
                            Id = 5,
                            AnoPublicacao = 2008,
                            Autor = "Robert C. Martin",
                            Categoria = "Tecnologia",
                            Descricao = "Guia essencial para desenvolvedores que desejam escrever código legível e sustentável.",
                            Disponivel = true,
                            ISBN = "978-85-0000-005-5",
                            Titulo = "Código Limpo"
                        },
                        new
                        {
                            Id = 6,
                            AnoPublicacao = -380,
                            Autor = "Platão",
                            Categoria = "Filosofia",
                            Descricao = "Obra fundamental da filosofia ocidental que discute justiça, política e a natureza da alma.",
                            Disponivel = false,
                            ISBN = "978-85-0000-006-6",
                            Titulo = "A República"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
